import {anatomyImage,anatomyMotion,assetUrl} from './livingAnatomy.js';
import {chapters,emergencyLessons} from './chapters.js';
import {escape} from './state.js';
export const currentChapterStep=s=>chapters[s.id]?.steps[s.step];
const circles=(points,color='#dfae8f')=>points.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="14" fill="${color}" stroke="#fff" stroke-width="2"/>`).join('');
const label=(x,y,text)=>`<text x="${x}" y="${y}" text-anchor="middle" fill="#176d73" font-size="15">${escape(text)}</text>`;
const icon=(x,y,text)=>`<g transform="translate(${x} ${y})"><circle r="36" fill="#fffdf3" stroke="#176d73" stroke-width="2"/><text y="10" text-anchor="middle" font-size="32" fill="#176d73">${text}</text></g>`;
export function chapterBoard(s){const def=currentChapterStep(s);let hotspots='';
 if(def?.kind==='coverage')hotspots=Array.from({length:def.count},(_,i)=>`<g data-chapter-value="${i}" class="chapter-hit"><circle cx="${s.id==='S3'?358:455+i*32}" cy="${s.id==='S3'?95+i*37:199}" r="18" fill="${s.hits?.includes(i)?'#76b5a0':'#6ab4d1'}" stroke="white" stroke-width="3"/><text x="${s.id==='S3'?358:455+i*32}" y="${(s.id==='S3'?95+i*37:199)+5}" text-anchor="middle" fill="#0b1f3a" font-size="14">${s.hits?.includes(i)?'✓':i+1}</text></g>`).join('');
 if(def?.kind==='sequence')hotspots=def.answers.map((answer,i)=>`<g data-chapter-value="${escape(answer)}" class="chapter-hit"><circle cx="${180+i*105}" cy="370" r="27" fill="${i<(s.hits?.length||0)?'#176d73':'#fff9e6'}" stroke="#d4a017" stroke-width="3"/><text x="${180+i*105}" y="376" text-anchor="middle" font-size="18" fill="${i<(s.hits?.length||0)?'#fff':'#0b1f3a'}">${i+1}</text></g>`).join('');
 if(def?.kind==='snap'){const [x,y]=def.target,[ox,oy]=def.origin;hotspots=`<rect x="${x-48}" y="${y-20}" width="96" height="40" rx="12" fill="#ffffff55" stroke="#176d73" stroke-width="3" stroke-dasharray="8 5"/><g data-chapter-drag transform="translate(${ox} ${oy})"><rect x="-48" y="-20" width="96" height="40" rx="12" fill="#f4d988" stroke="#b2933d" stroke-width="3"/>${label(0,45,'Drag piece')}</g>`;}
 if(def?.kind==='sort')hotspots=def.items.map((item,i)=>s.sorted?.includes(i)?'':`<g data-chapter-item="${i}" class="chapter-hit"><circle cx="${180+i*110}" cy="185" r="25" fill="${s.selected===i?'#d4a017':item.bin==='waste'?'#9c7da4':'#7db9ad'}" stroke="white" stroke-width="3"/><text x="${180+i*110}" y="191" text-anchor="middle" fill="white" font-size="17">${i+1}</text></g>`).join('');
 if(def?.kind==='wait')hotspots=`<g data-chapter-hold class="chapter-hit"><rect x="255" y="292" width="190" height="48" rx="15" fill="#fff4ca" stroke="#d4a017" stroke-width="3"/>${label(350,322,'Hold / observe model')}</g>`;
 const image=s.id.startsWith('E')?`${icon(260,160,'!')}${icon(440,160,'+')}<path d="M290 230H410" stroke="#176d73" stroke-width="6" stroke-dasharray="8 6"/>${label(350,295,'Stay safe. Get a trusted adult.')}${label(350,330,'Practice help decisions. No real call is made.')}`:s.id==='S10'&&s.step<4?`<image href="${assetUrl('MQ_S1_realistic_arm.webp')}" width="700" height="430" preserveAspectRatio="none"/>`:anatomyImage(s.id)+`<g class="motion-overlay">${anatomyMotion(s.id)}</g>`;
 return `<svg id="stage-svg" class="chapter-board" role="img" aria-label="Detailed illustrated anatomy: ${escape(chapters[s.id].title)}" viewBox="0 0 700 430"><rect width="700" height="430" rx="24" fill="#e3eee4"/>${image}<rect x="16" y="12" width="293" height="30" rx="8" fill="#fffdf1e8"/><text x="30" y="32" fill="#176d73" font-size="12" letter-spacing="1">ILLUSTRATED ANATOMY / PRACTICE</text>${hotspots}${!def?`<rect x="25" y="343" width="650" height="58" rx="14" fill="#edf5d8"/>${label(350,379,'✓ '+chapters[s.id].success)}`:''}</svg>`;
}
const command=(s,value,text,attrs='')=>`<button data-chapter-action data-step="${s.step}" data-value="${escape(value)}" ${attrs}>${escape(text)}</button>`;
export function chapterControls(s){const def=currentChapterStep(s);if(!def)return '';
 const progress=s.hits?.length||0;let body='';
 if(def.kind==='choice')body=`<p>${escape(def.question)}</p><div class="chapter-options">${def.options.map(v=>command(s,v,v)).join('')}</div>`;
 if(def.kind==='coverage')body=`<p>Diagram zones: ${progress}/${def.threshold}</p><div class="meter"><span style="width:${progress/def.threshold*100}%"></span></div><div class="chapter-options">${Array.from({length:def.count},(_,i)=>command(s,i,`Zone ${i+1}${s.hits?.includes(i)?' complete':''}`,s.hits?.includes(i)?'disabled':'')).join('')}</div>`;
 if(def.kind==='sequence')body=`<p>Follow the path: ${progress}/${def.answers.length}</p><div class="chapter-options">${def.answers.map((v,i)=>command(s,v,v,i<progress?'disabled':'')).join('')}</div>`;
 if(def.kind==='cards')body=`<div class="chapter-options">${def.options.map(v=>command(s,v,(s.chosen?.includes(v)?'✓ ':'')+v,s.chosen?.includes(v)?'disabled':'')).join('')}</div>`;
 if(def.kind==='snap')body=command(s,'snap','Place piece in outline (keyboard)','data-distance="0"');
 if(def.kind==='corridor')body=`<label class="range-control">Diagram position <input type="range" min="0" max="100" value="${s.range||50}" aria-label="Diagram position" id="chapter-range"></label><p>Green diagram range: ${def.min}–${def.max}</p>${command(s,'range','Check diagram position','data-range-check')}`;
 if(def.kind==='wait'){const begun=s.waitStarted!==undefined;body=`<div class="meter"><span id="chapter-wait-meter" style="width:0%"></span></div><p id="chapter-wait-status" role="status">${begun?'Demonstration in progress…':'Short game demonstration. Not a medical timer.'}</p>${begun?command(s,'finish','Check demonstration'):command(s,'start','Start short demonstration')}`;}
 if(def.kind==='sort')body=`<div class="chapter-options">${def.items.map((item,i)=>s.sorted?.includes(i)?`<span class="sorted-chip">✓ ${escape(item.label)}</span>`:command(s,'select',`${s.selected===i?'Selected: ':''}${item.label}`,`data-item="${i}"`)).join('')}</div><div class="chapter-options">${def.bins.map(([id,name])=>command(s,id,name)).join('')}</div><p>Sorted ${s.sorted?.length||0}/${def.items.length}</p>`;
 return `<div class="chapter-instruction"><p>${escape(def.instruction||'Notice, think, then choose.')}</p>${body}</div>`;
}
export function emergencyHub(progress){return `<div class="section-heading"><div><div class="eyebrow">EMERGENCY / CALM HELP PRACTICE</div><h1>Notice trouble. Get help.</h1><p>Three story lessons about safe decisions. No medical procedures, no real calls, and no time pressure.</p></div></div><div class="systems">${emergencyLessons.map(l=>`<button class="system-card" data-system="${l.id}"><span class="system-icon">+</span><div class="eyebrow">HELP STORY ${l.order}</div><h3>${escape(l.name)}</h3><p>${escape(l.operation)}</p><span class="status">${progress.completed.includes(l.id)?'✓ Help lesson saved':'Begin help lesson'} →</span></button>`).join('')}</div><p class="adult">In a real urgent emergency, get a trusted adult and call the local emergency number (911 in the United States). Do not wait for this game.</p>`;}
