// Additional curriculum missions. Every board is an educational simulation.
const choice=(label,question,options,answer,tool='')=>({label,kind:'choice',question,options,answer,tool});
const action=(label,kind,tool,instruction,extra={})=>({label,kind,tool,instruction,...extra});
const tool=(id,label,purpose)=>[id,label,purpose];
export const chapters={
 S3:{title:'Calm the Strain',success:'Supported and calm',prompts:['How do muscles and tendons help you move?','What should you do about a real painful muscle?'],steps:[choice('Notice the muscle','Which part pulls on bones?',['Muscle','Skin','Kidney'],'Muscle'),choice('Predict a gentle start','What comes first in this pretend comfort mission?',['Rest and ask an adult','Force a painful stretch'],'Rest and ask an adult'),action('Cool the diagram','coverage','ice','Cover four of the five comfort zones. This is a game meter, not a treatment duration.',{count:5,threshold:4}),action('Pause the activity','wait','rest','Watch a short simulation pause. It does not represent how long an injury needs to heal.',{duration:3000}),action('Explore a comfortable range','corridor','range','Move the healthy model marker into the green range. Never stretch a real painful muscle.',{min:40,max:60}),action('Add the pretend support','snap','wrap','Drag the support to its outline.',{target:[360,230],origin:[100,350],tolerance:38})],tools:[tool('ice','Cool pack','Cover the diagram comfort zones'),tool('rest','Rest cue','Pause this pretend activity'),tool('range','Range explorer','Explore a healthy model, never force pain'),tool('wrap','Support','Match the diagram outline')]},
 S4:{title:'Help the Clot Team',success:'The helper plug is protected',prompts:['Name one job of blood.','How do platelet helpers protect a small break?'],steps:[choice('Notice the vessel','Where does blood normally travel?',['Inside vessels','Outside skin'],'Inside vessels'),choice('Predict a protected plug','Which helps this pretend plug stay in place?',['A steady pad','Keep disturbing it'],'A steady pad'),action('Keep the diagram pad steady','wait','pressure','Hold the game pad steady for one short demonstration. This is not real first aid.',{duration:3000}),action('Match the support pose','corridor','support','Match the diagram token to the highlighted support position.',{min:65,max:85}),action('Observe the helpers','wait','observe','Watch the simulated platelet team gather inside the pipe.',{duration:3000}),action('Protect the pretend plug','snap','bandage','Place the bandage over the protected diagram site.',{target:[350,215],origin:[100,350],tolerance:38})],tools:[tool('pressure','Steady pad','Demonstrate support for a clot'),tool('support','Pose matcher','Match the diagram support token'),tool('observe','Helper viewer','Watch platelet helpers gather'),tool('bandage','Bandage','Protect the pretend plug')]},
 S5:{title:'Steady the Pump Path',success:'The loop is connected',prompts:['Is the heart a pump or a filter? Why?','Name one habit that supports a healthy heart.'],steps:[choice('Notice the pump','Which organ pumps blood?',['Heart','Stomach','Kidney'],'Heart'),choice('Predict the loop','What must this flow path have?',['A connected outward and return loop','A pipe with a missing section'],'A connected outward and return loop'),action('Listen at the pump','choice','listen','Choose the pump listening zone.',{question:'Where should the diagram listener go?',options:['Heart','Foot'],answer:'Heart'}),action('Reconnect the pipe','snap','coupler','Drag the pipe coupler into the missing section.',{target:[490,210],origin:[100,350],tolerance:36}),action('Open the rhythm gate','sequence','valve','Follow three slow numbered pulse cues.',{answers:['Pulse 1','Pulse 2','Pulse 3']}),action('Choose everyday habits','cards','habits','Choose two everyday habits that support wellbeing.',{options:['Enjoy active play','Get enough sleep','Smoke','Skip sleep'],answers:['Enjoy active play','Get enough sleep']})],tools:[tool('listen','Listener','Find the diagram heart'),tool('coupler','Pipe coupler','Reconnect the educational flow loop'),tool('valve','Rhythm gate','Follow the numbered pulse cues'),tool('habits','Habit cards','Choose everyday wellbeing habits')]},
 S7:{title:'Explore the Food Path',success:'Food follows the connected path',prompts:['List the food path in order.','How is digestion like a plumbing and processing system?'],steps:[choice('Notice the path','Where does the food path begin?',['Mouth','Kidney','Heart'],'Mouth'),choice('Predict the next stop','What comes after the food pipe?',['Stomach','Brain'],'Stomach'),action('Trace food in order','sequence','viewer','Follow the four labeled stops.',{answers:['Mouth','Esophagus','Stomach','Intestines']}),action('Find the diagram bend','choice','viewer','Notice where the game token has paused.',{question:'Where is the game token waiting?',options:['Pipe bend','Heart'],answer:'Pipe bend'}),action('Guide the model token','sequence','guide','Tap the three connected guide marks in order. Never try this on a person.',{answers:['Guide 1','Guide 2','Guide 3']}),action('Choose gentle habits','cards','habits','Choose water and an adult check-in. The game does not diagnose stomach pain.',{options:['Drink water when thirsty','Tell an adult about pain','Invent tummy surgery','Ignore severe pain'],answers:['Drink water when thirsty','Tell an adult about pain']})],tools:[tool('viewer','Path viewer','Explore where food travels'),tool('guide','Token guide','Move only the educational token'),tool('habits','Care cards','Choose water and adult help')]},
 S8:{title:'Clean the Filter',success:'Useful parts stay; waste moves on',prompts:['What do kidneys filter?','How does responding to thirst support your body?'],steps:[choice('Notice the filter','Which organs filter blood?',['Kidneys','Lungs','Bones'],'Kidneys'),choice('Predict the sorting job','What should the model filter keep?', ['Needed water and nutrients','Every waste token'],'Needed water and nutrients'),action('Sort the model contents','sort','sorter','Choose a token, then its bin. Kidneys keep useful material and remove wastes.',{items:[{label:'Waste token A',bin:'waste'},{label:'Useful nutrient',bin:'keep'},{label:'Waste token B',bin:'waste'},{label:'Useful water balance',bin:'keep'}],bins:[['waste','Remove waste'],['keep','Keep useful material']]}),action('Choose a water habit','choice','water','Choose a helpful everyday habit. No dose or quantity is taught.',{question:'When you notice thirst, what is a helpful habit?',options:['Drink water','Ignore thirst all day'],answer:'Drink water'}),action('Trace the leftover liquid','sequence','viewer','Follow the simplified urine pathway.',{answers:['Kidneys','Ureters','Bladder']})],tools:[tool('sorter','Filter sorter','Separate model waste and useful tokens'),tool('water','Water habit','Respond to thirst'),tool('viewer','Path viewer','Trace kidney to bladder')]},
 S9:{title:'Rest the Signal Hub',success:'An adult is helping; play stays paused',prompts:['Brain is a hub; nerves are like what?','What should you do after a real head bump with symptoms?'],safetyAnswer:1,steps:[choice('Notice the hub','What coordinates signals in this diagram?',['Brain','Stomach'],'Brain'),choice('Predict safe help','After a real head bump with symptoms, what comes first?',['Stop play and tell an adult','Keep playing to test yourself'],'Stop play and tell an adult'),action('Choose a calmer setting','choice','dimmer','Choose the quieter diagram environment.',{question:'Which setting is calmer?',options:['Quiet space','Loud flashing arcade'],answer:'Quiet space'}),action('Tell a trusted adult','choice','adult','Practice reporting what happened.',{question:'What should the character say?',options:['I bumped my head and do not feel right','Keep it secret'],answer:'I bumped my head and do not feel right'}),action('Pause the game activity','wait','quiet','A short game pause represents stopping play, not injury recovery. Real return to sport needs professional clearance.',{duration:3000}),action('Learn about the signal wires','choice','viewer','Identify a nerve. This quiz cannot assess an injury or clear someone to play.',{question:'What carries messages between brain and body?',options:['Nerves','Bandages'],answer:'Nerves'})],tools:[tool('dimmer','Quiet setting','Choose a calmer environment'),tool('adult','Adult helper','Report the bump and symptoms'),tool('quiet','Pause cue','Keep play paused'),tool('viewer','Signal viewer','Learn about nerves')]},
 S10:{title:'Call the Defense Team',success:'Barrier and helper teams work together',prompts:['Name two ways the body helps protect itself.','Name one habit that supports your wellbeing.'],steps:[choice('Notice the defense team','Which helpers are part of the immune system?',['White blood cells','Cast strips'],'White blood cells'),choice('Predict a clean start','Before snack, what helps remove germs from hands?',['Wash hands','Skip washing'],'Wash hands'),action('Clear the hand diagram','coverage','soap','Clear all five germ zones on this pretend hand.',{count:5,threshold:5}),action('Protect the barrier','snap','bandage','Match the protection patch to the skin-wall outline.',{target:[350,245],origin:[100,350],tolerance:38}),action('Match the cell team','sequence','cells','Send a model helper to each numbered germ zone in order.',{answers:['Zone 1','Zone 2','Zone 3']}),action('Choose supporting habits','cards','habits','Choose sleep and varied food. Doctors and vaccines are real-world helpers too.',{options:['Get enough sleep','Enjoy varied food','Skip sleep','Never wash hands'],answers:['Get enough sleep','Enjoy varied food']})],tools:[tool('soap','Handwash model','Remove the diagram germs'),tool('bandage','Barrier patch','Cover the skin-wall outline'),tool('cells','Cell team','Match helpers to germ zones'),tool('habits','Habit cards','Support everyday wellbeing')]}
};
export const emergencyLessons=[
 {id:'E1',order:1,name:'Someone cannot breathe',operation:'Get Help for Breathing Trouble',theme:'Recognize trouble and get an adult / emergency help',targets:['Trouble breathing can be an emergency.','Get a trusted adult and urgent help; do not wait for a game meter.','The game does not teach airway procedures or medicine dosing.'],anatomy:['Breathing','Adult helper','Emergency call'],scenarios:['A character is having serious trouble breathing at the playground.'],fairTest:'This is a decision lesson, not an experiment on a person.',journal:'What should you do to get urgent help?',status:'playable',steps:[]},
 {id:'E2',order:2,name:'A head bump during play',operation:'Pause Play and Tell an Adult',theme:'Report symptoms; professional assessment matters',targets:['A head bump with symptoms needs adult attention.','Stop play and tell an adult what happened.','A healthcare professional decides when return to sport is safe.'],anatomy:['Head','Brain','Adult helper'],scenarios:['A character feels dizzy after a ball hits their head.'],fairTest:'A game quiz cannot assess a head injury or clear return to sport.',journal:'What do you tell the adult?',status:'playable',steps:[]},
 {id:'E3',order:3,name:'An unsafe accident scene',operation:'Stay Safe and Call for Help',theme:'Keep yourself safe and report the location',targets:['Do not enter an unsafe place to help.','Get a trusted adult; urgent emergencies need local emergency services.','Tell the helper where you are and what you noticed.'],anatomy:['Safe area','Adult helper','Location'],scenarios:['A character has fallen near a busy road.'],fairTest:'Safe decisions come before any game task.',journal:'How can you get help while staying safe?',status:'playable',steps:[]}
];
for(const lesson of emergencyLessons){const breathing=lesson.id==='E1',head=lesson.id==='E2';chapters[lesson.id]={title:lesson.operation,success:'A safe help plan is ready',safetyAnswer:1,prompts:['What did you notice in this story?','How will you get adult or emergency help?'],tools:[],steps:[choice('Notice the story','What needs attention?',breathing?['Serious trouble breathing','A missing toy']:head?['Dizzy after a head bump','A forgotten game score']:['An accident near a busy road','A puzzle on a desk'],breathing?'Serious trouble breathing':head?'Dizzy after a head bump':'An accident near a busy road'),choice('Predict a safe response','What should the character do first?',head?['Stop play and tell a trusted adult','Return to the game immediately']:['Stay safe and get adult / emergency help','Try medical tools from the game'],head?'Stop play and tell a trusted adult':'Stay safe and get adult / emergency help'),action('Practice asking for help','sequence','','Choose the help messages in order. No real call is made.',{answers:['Tell a trusted adult','Describe the problem and location',breathing?'Get urgent emergency help':head?'Get professional advice; keep play paused':'Call local emergency services when urgent']}),choice('Observe the safe plan','What is true about this game?',['It helps me practice asking for help','It qualifies me to treat real injuries'],'It helps me practice asking for help')]};}
export const extendedSlices=Object.fromEntries(Object.entries(chapters).map(([id,chapter])=>[id,{spec:{id,title:chapter.title,steps:[...chapter.steps.map(s=>s.label),'Observe the outcome','Journal'],tools:chapter.tools,prompts:chapter.prompts},act:(s,a,now)=>chapterAct(s,a,now)}]));
export function chapterAct(s,a,now=Date.now()){
 const chapter=chapters[s.id],step=chapter.steps[s.step];
 if(!step)return 'Observe the outcome and write your journal.';
 if(a.type!=='chapter'||a.step!==s.step)return 'Follow the current checklist step first.';
 if(step.tool&&s.tool!==step.tool)return 'Select the matching tool before using the board.';
 s.hits??=[];s.chosen??=[];s.sorted??=[];s.range??=50;
 let done=false;
 if(step.kind==='choice'){if(a.value!==step.answer)return 'Take another look at the science and try a gentle redo.';done=true;}
 else if(step.kind==='coverage'){const index=Number(a.value);if(!Number.isInteger(index)||index<0||index>=step.count)return 'Choose a diagram zone.';if(!s.hits.includes(index))s.hits.push(index);done=s.hits.length>=step.threshold;}
 else if(step.kind==='sequence'){const expected=step.answers[s.hits.length];if(a.value!==expected)return `Follow the path in order. Next: ${expected}.`;s.hits.push(a.value);done=s.hits.length===step.answers.length;}
 else if(step.kind==='cards'){if(!step.answers.includes(a.value))return 'Choose a habit that supports wellbeing.';if(!s.chosen.includes(a.value))s.chosen.push(a.value);done=step.answers.every(v=>s.chosen.includes(v));}
 else if(step.kind==='corridor'){const value=Number(a.value);if(!Number.isFinite(value)||value<step.min||value>step.max)return 'Stay inside the green diagram range; never force pain.';s.range=value;done=true;}
 else if(step.kind==='snap'){if(!Number.isFinite(a.distance)||a.distance>step.tolerance)return 'Move the diagram piece closer to its glowing outline.';done=true;}
 else if(step.kind==='wait'){if(a.value==='start'){s.waitStarted??=now;return '';}if(a.value!=='finish'||s.waitStarted===undefined||now-s.waitStarted<step.duration)return 'Let this short demonstration finish first.';done=true;}
 else if(step.kind==='sort'){if(a.item!==undefined){if(!Number.isInteger(a.item)||a.item<0||a.item>=step.items.length||s.sorted.includes(a.item))return 'Choose a remaining filter token.';s.selected=a.item;return '';}if(s.selected===undefined)return 'Choose a token before its bin.';if(a.value!==step.items[s.selected].bin)return 'This token belongs in the other bin. Try again.';s.sorted.push(s.selected);s.selected=undefined;done=s.sorted.length===step.items.length;}
 if(done){s.step++;s.hits=[];s.chosen=[];s.sorted=[];s.selected=undefined;s.waitStarted=undefined;s.tool='';}
 return '';
}
