import * as THREE from 'three';
export const layers={Skin:[['Skin','The outer shield helps keep germs out.','S1']],Muscle:[['Muscles','Muscles pull on bones to move your body.','S3'],['Tendons','Tendons connect muscles to bones.','S3']],Bone:[['Bones','The hard frame supports and protects your body.','S2'],['Joints','Joints let your bones bend and turn.','S2']],Organs:[['Heart','The heart pumps blood around a loop.','S5'],['Lungs','Lungs take oxygen in and send carbon dioxide out.','S6'],['Stomach','The stomach helps break down food.','S7'],['Kidneys','Kidneys filter waste from blood.','S8']],Pipes:[['Arteries','Arteries carry blood away from the heart.','S5'],['Veins','Veins carry blood back toward the heart.','S5']],Signals:[['Brain','The brain is the control hub.','S9'],['Nerves','Nerves carry messages around the body.','S9']]};
export function mountLab(host,layer,onPart){let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{host.innerHTML='<div class="lab-fallback">Your anatomy labels are ready below. This device does not support the 3D exhibit.</div>';return ()=>{}}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive 3D anatomy exhibit. Use the part buttons for keyboard exploration.');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,1,.1,100);camera.position.set(0,0,13);scene.add(new THREE.HemisphereLight(0xfff7e4,0x176d73,2.8));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(4,5,6);scene.add(light);const group=new THREE.Group();scene.add(group);const meshes=[];
 function ellipsoid(x,y,z,sx,sy,sz,color,part,opacity=1){const m=new THREE.Mesh(new THREE.SphereGeometry(1,32,24),new THREE.MeshStandardMaterial({color,roughness:.43,transparent:opacity<1,opacity}));m.position.set(x,y,z);m.scale.set(sx,sy,sz);group.add(m);if(part!==null&&part!==undefined){m.userData.part=part;meshes.push(m)}return m}
 const skin=layer==='Skin';const pale=skin?0xe3b78e:0x85b9b4;const op=skin?1:.16;
 ellipsoid(0,2.65,0,.62,.76,.56,pale,skin?0:null,op);ellipsoid(0,.8,0,1.02,1.6,.49,pale,skin?0:null,op);for(const x of [-1,1]){ellipsoid(x*1.25,.7,0,.3,1.43,.31,pale,skin?0:null,op);ellipsoid(x*.5,-1.9,0,.39,1.4,.36,pale,skin?0:null,op)}
 if(layer==='Bone'){ellipsoid(0,2.65,.2,.48,.58,.4,0xfff7da,0);for(const x of [-1,1]){ellipsoid(x*.52,-1.7,.3,.12,1.36,.12,0xfff7da,0);ellipsoid(x*1.25,.7,.3,.1,1.3,.1,0xfff7da,0);ellipsoid(x*.52,-.45,.32,.24,.24,.2,0xd4a017,1)}for(let i=0;i<6;i++)ellipsoid(0,1.6-i*.24,.2,.68,.09,.32,0xfff7da,0);ellipsoid(0,.7,.3,.11,1.2,.15,0xfff7da,0)}
 if(layer==='Muscle'){for(const x of [-1,1]){ellipsoid(x*1.25,1.1,.28,.23,.72,.18,0xe8836b,0);ellipsoid(x*.5,-1.4,.3,.28,.85,.22,0xe8836b,0);ellipsoid(x*.5,-2.5,.3,.08,.35,.08,0xf5dfaf,1)}ellipsoid(0,1.1,.3,.8,.9,.2,0xe8836b,0)}
 if(layer==='Organs'){ellipsoid(-.12,1.15,.67,.3,.42,.25,0xd97966,0);ellipsoid(-.55,1.4,.3,.37,.73,.22,0xebbcac,1);ellipsoid(.55,1.4,.3,.37,.73,.22,0xebbcac,1);ellipsoid(.24,.1,.52,.46,.39,.27,0xd4a017,2);ellipsoid(-.6,-.2,.3,.22,.36,.17,0x906b8b,3);ellipsoid(.6,-.2,.3,.22,.36,.17,0x906b8b,3)}
 if(layer==='Signals'){ellipsoid(0,2.7,.5,.43,.35,.23,0xd4a017,0);for(const x of [-1,1]){ellipsoid(x*.6,.55,.5,.035,1.7,.035,0xf5c759,1);ellipsoid(x*1.2,.5,.45,.035,1.1,.035,0xf5c759,1)}}
 const flow=[];if(layer==='Pipes'){for(const x of [-1,1]){ellipsoid(x*.3,.4,.5,.075,2.1,.075,x<0?0xe8836b:0x469ebd,x<0?0:1);for(let i=0;i<9;i++){const m=ellipsoid(x*.3,-1.5+i*.45,.61,.055,.055,.055,0xffefd1,x<0?0:1);flow.push({m,dir:x})}}}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();const click=e=>{const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(meshes)[0];if(hit)onPart(hit.object.userData.part)};renderer.domElement.addEventListener('click',click);
 const resize=()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(host);resize();let frame,old=performance.now();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function animate(t){frame=requestAnimationFrame(animate);const dt=Math.min((t-old)/1000,.05);old=t;if(!reduced){group.rotation.y=Math.sin(t*.0003)*.16;for(const f of flow){f.m.position.y+=dt*f.dir*.6;if(f.m.position.y>2.4)f.m.position.y=-1.5;if(f.m.position.y< -1.5)f.m.position.y=2.4}}renderer.render(scene,camera)}frame=requestAnimationFrame(animate);
 return ()=>{cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener('click',click);scene.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose()});renderer.dispose()};}
