import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mountLab as mountFallback} from './freeLabFallback.js';
export const layers={Skin:[['Skin','Skin forms the outer barrier and helps you sense touch.','S1']],Muscle:[['Muscles','Muscles pull on bones to move your body.','S3'],['Tendons','Tendons connect muscles to bones.','S3']],Bone:[['Bones','The skeleton supports the body and protects organs.','S2'],['Joints','Joints are places where bones meet and movement can happen.','S2']],Organs:[['Heart','The heart pumps blood through the lungs and body.','S5'],['Lungs','Lungs exchange oxygen and carbon dioxide with blood.','S6'],['Stomach','The stomach mixes food and begins breaking it down.','S7'],['Kidneys','Kidneys filter waste and extra water from blood.','S8'],['Intestines','Intestines absorb nutrients and water and move leftover waste along.','S7']],Pipes:[['Arteries','Arteries carry blood away from the heart.','S5'],['Veins','Veins carry blood back toward the heart.','S5']],Signals:[['Brain','The brain coordinates movement, senses, memory and thinking.','S9'],['Nerves','Nerves carry signals between the brain, spinal cord and body.','S9']]};
export function anatomyTag(object){let node=object;while(node){if(node.userData?.layer)return {layer:node.userData.layer,part:node.userData.part};node=node.parent}return {}}
let assetPromise;
function loadHuman(){if(!assetPromise)assetPromise=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).loadAsync(`${import.meta.env.BASE_URL}assets/models/MQ_human_anatomy.glb`).then(g=>g.scene).catch(e=>{assetPromise=null;throw e});return assetPromise}
export function mountLab(host,layer,onPart){let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{host.insertAdjacentHTML('beforeend','<div class="lab-fallback">Your anatomy labels are ready below. This device does not support the 3D exhibit.</div>');return ()=>{}}
 const status=document.createElement('div');status.className='model-status';status.setAttribute('role','status');status.textContent='Preparing your human anatomy exhibit…';host.append(status);
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.append(renderer.domElement);
 renderer.domElement.setAttribute('aria-label','Human anatomy model. Drag to turn, scroll to zoom, or use the rotate and part buttons.');renderer.domElement.style.touchAction='none';
 const viewTarget=layer==='Organs'?.32:.02;const viewDistance=layer==='Organs'?1.85:3.95;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(30,1,.02,40);camera.position.set(.06,viewTarget+.1,viewDistance);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,viewTarget,0);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=1.35;controls.maxDistance=5;controls.minPolarAngle=.4;controls.maxPolarAngle=Math.PI-.4;
 scene.add(new THREE.HemisphereLight(0xfff5e7,0x667f83,2.0));const key=new THREE.DirectionalLight(0xfff7ef,3.6);key.position.set(-2.5,4,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-1;key.shadow.camera.right=1;key.shadow.camera.top=1.2;key.shadow.camera.bottom=-1.2;key.shadow.bias=-.0003;scene.add(key);const fill=new THREE.DirectionalLight(0xe3edf9,2.2);fill.position.set(3,1,2);scene.add(fill);const rim=new THREE.DirectionalLight(0xe5ffed,2);rim.position.set(0,3,-3);scene.add(rim);
 const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(.49,.52,.035,64),new THREE.MeshStandardMaterial({color:0xcedbd1,roughness:.8}));pedestal.position.y=-.91;pedestal.receiveShadow=true;scene.add(pedestal);
 const shadow=new THREE.Mesh(new THREE.PlaneGeometry(8,8),new THREE.ShadowMaterial({opacity:.12}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-.93;shadow.receiveShadow=true;scene.add(shadow);
 const buttons=document.createElement('div');buttons.className='model-controls';buttons.setAttribute('role','group');buttons.setAttribute('aria-label','Model viewing controls');buttons.innerHTML='<button type="button" data-model-turn="-1" aria-label="Turn model left">↶</button><button type="button" data-model-front>Front view</button><button type="button" data-model-turn="1" aria-label="Turn model right">↷</button><button type="button" data-model-zoom="in" aria-label="Zoom model in">+</button><button type="button" data-model-zoom="out" aria-label="Zoom model out">−</button>';host.append(buttons);
 let model=null,alive=true,frame,fallbackDispose=null,highlighted=null,holdUntil=0;const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),materials=[],meshes=[],moving=[],breathing=[],flow=[];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const defaultDistance=()=>Math.max(viewDistance,(layer==='Organs'?.23:.46)/(Math.tan(THREE.MathUtils.degToRad(15))*camera.aspect));
 const buttonClick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-model-front')){if(model)model.rotation.y=0;camera.position.set(.06,viewTarget+.1,defaultDistance());controls.target.set(0,viewTarget,0);controls.update()}if(b.dataset.modelTurn&&model)model.rotation.y+=Number(b.dataset.modelTurn)*Math.PI/8;if(b.dataset.modelZoom){const delta=camera.position.clone().sub(controls.target);delta.multiplyScalar(b.dataset.modelZoom==='in'?.82:1.22);delta.clampLength(controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(delta);controls.update()}};buttons.addEventListener('click',buttonClick);
 const showPart=label=>{const index=layers[layer].findIndex(p=>p[0]===label);if(index<0)return;onPart(index);if(highlighted)highlighted.material.emissive.setHex(0);highlighted=meshes.find(m=>m.userData.part===label);if(highlighted){highlighted.material.emissive.setHex(0x254237);highlighted.material.emissiveIntensity=.3;holdUntil=performance.now()+1300}};
 let startPointer=null;const down=e=>{startPointer=[e.clientX,e.clientY]};const up=e=>{if(!startPointer||Math.hypot(e.clientX-startPointer[0],e.clientY-startPointer[1])>8){startPointer=null;return}startPointer=null;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(meshes)[0];if(hit)showPart(hit.object.userData.part)};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);
 const resize=()=>{const w=host.clientWidth,h=Math.max(300,host.clientHeight-116);renderer.setSize(w,h);camera.aspect=w/h;camera.position.z=defaultDistance();camera.updateProjectionMatrix();controls.update()};const observer=new ResizeObserver(resize);observer.observe(host);resize();
 loadHuman().then(source=>{if(!alive)return;model=source.clone(true);model.position.y=-.88;scene.add(model);model.updateMatrixWorld(true);const floorY=new THREE.Box3().setFromObject(model).min.y;pedestal.position.y=floorY-.0175;shadow.position.y=floorY-.036;model.traverse(o=>{if(!o.isMesh)return;Object.assign(o.userData,anatomyTag(o));o.material=o.material.clone();materials.push(o.material);o.castShadow=true;o.receiveShadow=true;const l=o.userData.layer;const inside=layer!=='Skin';o.visible=l===layer||l==='Skin'||(!inside&&(l==='Face'||l==='Clothing'));if(l==='Skin'){if(o.morphTargetDictionary?.Breath!==undefined)breathing.push(o);o.material.normalScale?.set(.22,.22);if(inside){o.material.map=null;o.material.normalMap=null;o.material.roughnessMap=null;o.material.vertexColors=false;o.material.side=THREE.FrontSide;o.material.transparent=true;o.material.opacity=.045;o.material.depthWrite=false;o.material.color.setHex(0xc8ddd4);o.castShadow=false;o.renderOrder=5}}if(o.visible&&l===layer){const part=o.userData.part;const i=layers[layer].findIndex(p=>p[0]===part);if(i>=0)meshes.push(o);if(layer==='Organs'&&['Lungs','Heart'].includes(part))moving.push({o,scale:o.scale.clone(),part})}});
 if(layer==='Pipes'){for(const sign of [-1,1]){const offset=sign<0?0:.012;const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(sign*(.016+offset),1.36,.042),new THREE.Vector3(sign*(.018+offset),1.15,.047),new THREE.Vector3(sign*(.024+offset),.94,.038),new THREE.Vector3(sign*(.092+offset),.77,.034),new THREE.Vector3(sign*(.106+offset),.48,.036),new THREE.Vector3(sign*(.103+offset),.14,.019)]);for(let i=0;i<10;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.002,8,6),new THREE.MeshBasicMaterial({color:sign<0?0xf5b893:0xa8dff0}));model.add(m);flow.push({m,curve,phase:i/10,sign})}}}
 status.textContent='Simplified human anatomy · Drag to turn · Scroll to zoom';status.classList.add('ready');host.dataset.modelState='ready';
 }).catch(()=>{if(!alive)return;status.textContent='Human model could not load. Showing the basic exhibit.';cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.dispose();renderer.domElement.remove();buttons.remove();scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose()});host.dataset.modelState='fallback';fallbackDispose=mountFallback(host,layer,onPart)});
 function animate(t){if(!alive||fallbackDispose)return;frame=requestAnimationFrame(animate);if(model&&!reduced){for(const o of breathing)o.morphTargetInfluences[o.morphTargetDictionary.Breath]=(Math.sin(t*.0012)+1)*.5;for(const {o,scale,part} of moving){const beat=part==='Heart'?Math.pow(Math.max(0,Math.sin(t*.006)),5)*.025:Math.sin(t*.0012)*.018;o.scale.copy(scale);o.scale.x*=1+beat;o.scale.z*=1+beat;o.scale.y*=1+beat*(part==='Heart'?1:.25)}for(const f of flow)f.m.position.copy(f.curve.getPointAt(((f.phase+t*.000055*f.sign)%1+1)%1))}if(highlighted&&t>holdUntil){highlighted.material.emissive.setHex(0);highlighted=null}controls.update();renderer.render(scene,camera)}frame=requestAnimationFrame(animate);
 return ()=>{alive=false;cancelAnimationFrame(frame);observer.disconnect();fallbackDispose?.();buttons.removeEventListener('click',buttonClick);renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',up);controls.dispose();for(const m of materials)m.dispose();for(const f of flow){f.m.geometry.dispose();f.m.material.dispose()}pedestal.geometry.dispose();pedestal.material.dispose();shadow.geometry.dispose();shadow.material.dispose();renderer.dispose()};
}
