import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {installArmMotion,createCirculation,motionAt,heartPulse} from './labMotion.js';
import {studioEnvironment,humanMaterial,portraitTarget} from './labAppearance.js';
import {mountLab as mountFallback} from './freeLabFallback.js';
export const layers={Skin:[['Skin','Skin forms the outer barrier and helps you sense touch.','S1']],Muscle:[['Muscles','Muscles pull on bones to move your body.','S3'],['Tendons','Tendons connect muscles to bones.','S3']],Bone:[['Bones','The skeleton supports the body and protects organs.','S2'],['Joints','Joints are places where bones meet and movement can happen.','S2']],Organs:[['Heart','The heart pumps blood through the lungs and body.','S5'],['Lungs','Lungs exchange oxygen and carbon dioxide with blood.','S6'],['Stomach','The stomach mixes food and begins breaking it down.','S7'],['Kidneys','Kidneys filter waste and extra water from blood.','S8'],['Intestines','Intestines absorb nutrients and water and move leftover waste along.','S7']],Pipes:[['Arteries','Arteries carry blood away from the heart.','S5'],['Veins','Veins carry blood back toward the heart.','S5']],Signals:[['Brain','The brain coordinates movement, senses, memory and thinking.','S9'],['Nerves','Nerves carry signals between the brain, spinal cord and body.','S9']]};
export function anatomyTag(object){let node=object;while(node){if(node.userData?.layer)return {layer:node.userData.layer,part:node.userData.part};node=node.parent}return {}}
let assetPromise;
function loadHuman(){if(!assetPromise)assetPromise=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).loadAsync(`${import.meta.env.BASE_URL}assets/models/MQ_human_anatomy.glb`).then(g=>g.scene).catch(e=>{assetPromise=null;throw e});return assetPromise}
export function mountLab(host,layer,onPart){let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{host.insertAdjacentHTML('beforeend','<div class="lab-fallback">Your anatomy labels are ready below. This device does not support the 3D exhibit.</div>');return ()=>{}}
 const status=document.createElement('div');status.className='model-status';status.setAttribute('role','status');status.textContent='Preparing your human anatomy exhibit…';host.append(status);
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.VSMShadowMap;host.append(renderer.domElement);
 renderer.domElement.setAttribute('aria-label','Human anatomy model. Drag to turn, scroll to zoom, or use the rotate and part buttons.');renderer.domElement.style.touchAction='none';
 const viewTarget=layer==='Organs'?.32:.02;const viewDistance=layer==='Organs'?1.85:3.95;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(30,1,.02,40);camera.position.set(.06,viewTarget+.1,viewDistance);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,viewTarget,0);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=.28;controls.maxDistance=5;controls.minPolarAngle=.4;controls.maxPolarAngle=Math.PI-.4;
 const disposeEnvironment=studioEnvironment(renderer,scene);scene.add(new THREE.HemisphereLight(0xfff4eb,0x827b75,.5));const key=new THREE.DirectionalLight(0xfff7ef,1.8);key.position.set(-2.5,4,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-1;key.shadow.camera.right=1;key.shadow.camera.top=1.2;key.shadow.camera.bottom=-1.2;key.shadow.bias=-.0003;key.shadow.radius=4;key.shadow.blurSamples=8;scene.add(key);const fill=new THREE.DirectionalLight(0xe3edf9,.65);fill.position.set(3,1,2);scene.add(fill);const rim=new THREE.DirectionalLight(0xffeee0,.4);rim.position.set(0,3,-3);scene.add(rim);
 const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(.49,.52,.035,64),new THREE.MeshStandardMaterial({color:0xcedbd1,roughness:.8}));pedestal.position.y=-.91;pedestal.receiveShadow=true;scene.add(pedestal);
 const shadow=new THREE.Mesh(new THREE.PlaneGeometry(8,8),new THREE.ShadowMaterial({opacity:.08}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-.93;shadow.receiveShadow=true;scene.add(shadow);
 const buttons=document.createElement('div');buttons.className='model-controls';buttons.setAttribute('role','group');buttons.setAttribute('aria-label','Model viewing controls');buttons.innerHTML='<button type="button" data-model-turn="-1" aria-label="Turn model left">↶</button><button type="button" data-model-front>Full body</button><button type="button" data-model-portrait>Face close-up</button><button type="button" data-model-turn="1" aria-label="Turn model right">↷</button><button type="button" data-model-zoom="in" aria-label="Zoom model in">+</button><button type="button" data-model-zoom="out" aria-label="Zoom model out">−</button>';host.append(buttons);
 const motion=document.createElement('div');motion.className='lab-motion-controls';motion.setAttribute('role','group');motion.setAttribute('aria-label','Body movement and blood flow');motion.innerHTML='<div class="motion-actions"><button data-body-motion="bend" aria-pressed="true">Bend arm</button><button data-body-motion="hold" aria-pressed="false">Hold bend</button><button data-body-motion="breathe" aria-pressed="false">Breathe</button><button data-motion-pause aria-pressed="false">Pause motion</button></div><div class="motion-actions"><button data-blood-toggle aria-pressed="false">Show blood flow</button><button data-flow-speed aria-pressed="false">Slow flow</button><button data-flow-focus>Follow cells</button></div><p class="flow-legend" hidden>Blood is always red. Follow cells: heart → body → heart → lungs → heart. Cells are enlarged; vessel colors and speed are simplified.</p>';host.append(motion);
 let model=null,alive=true,frame,fallbackDispose=null,highlighted=null,holdUntil=0;const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),materials=[],meshes=[],moving=[],breathing=[],motionDisposers=[];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 let motionMode='bend',paused=reduced,showBlood=['Pipes','Organs'].includes(layer),slowFlow=false,flowFocused=false,portraitFocused=false,elapsed=0,flowElapsed=0,lastTime=null,circulation=null;const bendUniform={value:0};
 const syncMotion=()=>{for(const b of motion.querySelectorAll('[data-body-motion]'))b.setAttribute('aria-pressed',String(b.dataset.bodyMotion===motionMode));const pause=motion.querySelector('[data-motion-pause]');pause.textContent=paused?'Resume motion':'Pause motion';pause.setAttribute('aria-pressed',String(paused));const blood=motion.querySelector('[data-blood-toggle]');blood.textContent=showBlood?'Hide blood flow':'Show blood flow';blood.setAttribute('aria-pressed',String(showBlood));motion.querySelector('[data-flow-speed]').setAttribute('aria-pressed',String(slowFlow));motion.querySelector('.flow-legend').hidden=!showBlood;motion.querySelector('[data-flow-focus]').textContent=flowFocused?'Body view':'Follow cells';host.dataset.motionState=paused?'paused':motionMode;host.dataset.bloodFlow=showBlood?'visible':'hidden';if(circulation)circulation.group.visible=showBlood;if(model)model.traverse(o=>{if(!o.isMesh||!o.userData.layer)return;const l=o.userData.layer;if(l==='Skin'){const transparent=layer!=='Skin'||showBlood;o.material.transparent=transparent;o.material.opacity=transparent?.14:1;o.material.depthWrite=!transparent;o.castShadow=!transparent;o.material.needsUpdate=true}if(l==='Pipes'&&!o.parent?.name.includes('circulation'))o.visible=layer==='Pipes'&&!showBlood;if(l==='Organs'&&['Heart','Lungs'].includes(o.userData.part))o.visible=layer==='Organs'||showBlood})};
 const motionClick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.bodyMotion){motionMode=b.dataset.bodyMotion;elapsed=0;if(!reduced)paused=false}if(b.hasAttribute('data-motion-pause'))paused=!paused;if(b.hasAttribute('data-blood-toggle'))showBlood=!showBlood;if(b.hasAttribute('data-flow-speed'))slowFlow=!slowFlow;if(b.hasAttribute('data-flow-focus')&&model){portraitFocused=false;flowFocused=!flowFocused;if(flowFocused){showBlood=true;const target=model.localToWorld(new THREE.Vector3(.112,.49,.036));controls.target.copy(target);camera.position.copy(target).add(new THREE.Vector3(0,.015,.42))}else{camera.position.set(.06,viewTarget+.1,defaultDistance());controls.target.set(0,viewTarget,0)}controls.update()}syncMotion()};motion.addEventListener('click',motionClick);syncMotion();
 const defaultDistance=()=>Math.max(viewDistance,(layer==='Organs'?.23:.46)/(Math.tan(THREE.MathUtils.degToRad(15))*camera.aspect));
 const buttonClick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-model-front')){portraitFocused=false;flowFocused=false;syncMotion();if(model)model.rotation.y=0;camera.position.set(.06,viewTarget+.1,defaultDistance());controls.target.set(0,viewTarget,0);controls.update()}if(b.hasAttribute('data-model-portrait')&&model){portraitFocused=true;flowFocused=false;syncMotion();model.rotation.y=0;controls.target.copy(portraitTarget);camera.position.copy(portraitTarget).add(new THREE.Vector3(.015,.015,.57));controls.update()}if(b.dataset.modelTurn&&model)model.rotation.y+=Number(b.dataset.modelTurn)*Math.PI/8;if(b.dataset.modelZoom){const delta=camera.position.clone().sub(controls.target);delta.multiplyScalar(b.dataset.modelZoom==='in'?.82:1.22);delta.clampLength(controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(delta);controls.update()}};buttons.addEventListener('click',buttonClick);
 const showPart=label=>{const index=layers[layer].findIndex(p=>p[0]===label);if(index<0)return;onPart(index);if(highlighted)highlighted.material.emissive.setHex(0);highlighted=meshes.find(m=>m.userData.part===label);if(highlighted){highlighted.material.emissive.setHex(0x254237);highlighted.material.emissiveIntensity=.3;holdUntil=performance.now()+1300}};
 let startPointer=null;const down=e=>{startPointer=[e.clientX,e.clientY]};const up=e=>{if(!startPointer||Math.hypot(e.clientX-startPointer[0],e.clientY-startPointer[1])>8){startPointer=null;return}startPointer=null;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(meshes)[0];if(hit)showPart(hit.object.userData.part)};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);
 const resize=()=>{const w=host.clientWidth,h=Math.max(300,host.clientHeight-(host.clientWidth<400?292:236));renderer.setSize(w,h);camera.aspect=w/h;if(!flowFocused&&!portraitFocused)camera.position.z=defaultDistance();camera.updateProjectionMatrix();controls.update()};const observer=new ResizeObserver(resize);observer.observe(host);resize();
 loadHuman().then(source=>{if(!alive)return;model=source.clone(true);model.position.y=-.88;scene.add(model);model.updateMatrixWorld(true);const floorY=new THREE.Box3().setFromObject(model).min.y;pedestal.position.y=floorY-.0175;shadow.position.y=floorY-.036;model.traverse(o=>{if(!o.isMesh)return;Object.assign(o.userData,anatomyTag(o));const l=o.userData.layer;o.material=humanMaterial(o.material,l,o.userData.part);materials.push(o.material);o.castShadow=true;o.receiveShadow=l!=='Skin';const inside=layer!=='Skin';o.visible=l===layer||l==='Skin'||(!inside&&(l==='Face'||l==='Clothing'));if(l==='Skin'){if(o.morphTargetDictionary?.Breath!==undefined)breathing.push(o);if(inside){o.material.map=null;o.material.normalMap=null;o.material.roughnessMap=null;o.material.vertexColors=false;o.material.side=THREE.FrontSide;o.material.transparent=true;o.material.opacity=.045;o.material.depthWrite=false;o.material.color.setHex(0xc8ddd4);o.castShadow=false;o.renderOrder=5}}if(l==='Organs'&&['Lungs','Heart'].includes(o.userData.part))moving.push({o,scale:o.scale.clone(),part:o.userData.part});if(l!=='Clothing')motionDisposers.push(installArmMotion(o,model,bendUniform));if(o.visible&&l===layer){const part=o.userData.part;const i=layers[layer].findIndex(p=>p[0]===part);if(i>=0)meshes.push(o);}});
 circulation=createCirculation();model.add(circulation.group);model.updateMatrixWorld(true);for(const mesh of circulation.vessels){motionDisposers.push(installArmMotion(mesh,model,bendUniform));if(layer==='Pipes')meshes.push(mesh)}host.dataset.bloodCellCount=String(circulation.cellCount);syncMotion();
 status.textContent='Simplified human anatomy · Drag to turn · Scroll to zoom';status.classList.add('ready');host.dataset.modelState='ready';
 }).catch(()=>{if(!alive)return;status.textContent='Human model could not load. Showing the basic exhibit.';cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.dispose();renderer.domElement.remove();buttons.remove();motion.remove();scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose()});host.dataset.modelState='fallback';fallbackDispose=mountFallback(host,layer,onPart)});
 function animate(t){if(!alive||fallbackDispose)return;frame=requestAnimationFrame(animate);const dt=lastTime===null?0:Math.min((t-lastTime)/1000,.05);lastTime=t;if(!paused&&!document.hidden){elapsed+=dt;flowElapsed+=dt*(slowFlow?.45:1)*(1+heartPulse(elapsed)*3)}
 if(model){bendUniform.value=motionAt(elapsed,motionMode);for(const o of breathing)o.morphTargetInfluences[o.morphTargetDictionary.Breath]=(1-Math.cos(elapsed*Math.PI/2.5))*.5;
 for(const {o,scale,part} of moving){const expansion=part==='Heart'?heartPulse(elapsed):Math.sin(elapsed*Math.PI/2.5)*.035;o.scale.copy(scale);o.scale.x*=1+expansion;o.scale.z*=1+expansion;o.scale.y*=1+expansion*(part==='Heart'?1:.25)}
 if(circulation&&showBlood)circulation.update(flowElapsed,bendUniform.value);
 }if(highlighted&&t>holdUntil){highlighted.material.emissive.setHex(0);highlighted=null}controls.update();renderer.render(scene,camera)}frame=requestAnimationFrame(animate);
 return ()=>{alive=false;cancelAnimationFrame(frame);observer.disconnect();fallbackDispose?.();buttons.removeEventListener('click',buttonClick);renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',up);controls.dispose();for(const m of materials)m.dispose();circulation?.dispose();for(const disposeMotion of motionDisposers)disposeMotion();motion.removeEventListener('click',motionClick);pedestal.geometry.dispose();pedestal.material.dispose();shadow.geometry.dispose();shadow.material.dispose();disposeEnvironment();renderer.dispose()};
}
