// Shared illustrated anatomy and motion for lessons and the close-up laboratory.
export const anatomyScenes={
 S1:{name:'Skin',asset:'MQ_S1_realistic_arm.webp',motion:'Touch travels from skin to nerves.',detail:'The skin is a living barrier, with sensation supplied by nerves.'},
 S2:{name:'Bones',asset:'MQ_R4_museum.webp',motion:'Bones support the hand; joints let it move.',detail:'The radius and ulna support the forearm. Muscles pull through tendons to move bones.'},
 S3:{name:'Muscles',asset:'MQ_R13_museum.webp',motion:'Watch the muscle shorten and relax.',detail:'A contracting muscle pulls on its tendon. This highlighted movement is an enlarged illustration.'},
 S4:{name:'Blood',asset:'MQ_R10_museum.webp',motion:'Red cells flow past a protected platelet plug.',detail:'Red blood cells carry oxygen. Platelets help seal a small break in a vessel wall.'},
 S5:{name:'Heart',asset:'MQ_R2_museum.webp',motion:'Follow the heartbeat and the outward / return loop.',detail:'The heart pumps blood to the lungs and body. Red cells stay red at both oxygen levels.'},
 S6:{name:'Lungs',asset:'MQ_R3_museum.webp',motion:'Air moves in and out as the lungs expand and relax.',detail:'Oxygen moves from air in the lungs into blood; carbon dioxide moves from blood into air.'},
 S7:{name:'Digestion',asset:'MQ_R14_museum.webp',motion:'Follow food from the esophagus toward the intestines.',detail:'Muscle contractions move food along. Digestion breaks food down and the intestines absorb nutrients.'},
 S8:{name:'Kidneys',asset:'MQ_R15_museum.webp',motion:'Follow filtered waste liquid down the ureters.',detail:'Kidneys filter blood. Waste and extra water become urine, which travels to the bladder.'},
 S9:{name:'Nerves',asset:'MQ_R16_museum.webp',motion:'Follow a signal from the brain toward the hand.',detail:'Nerve cells carry electrical and chemical signals. The traveling light is a teaching convention.'},
 S10:{name:'Defense',asset:'MQ_R17_museum.webp',motion:'Watch immune helpers move among the blood cells.',detail:'White blood cells help protect the body. Skin and handwashing also help keep germs out.'}
};
export const assetUrl=name=>`${import.meta.env?.BASE_URL||'/'}assets/anatomy/${name}`;
export function anatomyImage(id,attrs=''){return `<image href="${assetUrl(anatomyScenes[id].asset)}" width="700" height="430" preserveAspectRatio="none" ${attrs}/>`}
const particle=(route,i,color='#fff2ad',size=5,duration=6)=>`<circle class="anatomy-particle anatomy-motion" r="${size}" fill="${color}" stroke="#fff" stroke-width="1" style="offset-path:path('${route}');animation-duration:${duration}s;animation-delay:-${i*duration/6}s"/>`;
const cells=(route,count=9,duration=9)=>Array.from({length:count},(_,i)=>`<g class="anatomy-particle anatomy-motion" style="offset-path:path('${route}');animation-duration:${duration}s;animation-delay:-${i*duration/count}s"><image href="${assetUrl('MQ_red_cell.webp')}" x="-14" y="-14" width="28" height="28" transform="rotate(${i*37})"/></g>`).join('');
export function anatomyMotion(id){
 if(id==='S4')return cells('M -25 180 C 200 190 240 235 365 254 S 550 291 725 278',14,10);
 if(id==='S10')return cells('M 90 265 C 230 280 450 275 600 257',8,12)+Array.from({length:3},(_,i)=>particle('M 135 205 Q 330 160 565 218',i,'#fff6e1',8,17)).join('');
 if(id==='S5')return `<path d="M350 180 C240 105 150 175 150 275 C150 360 545 365 545 265 Q545 210 490 210 Q440 125 385 175" fill="none" stroke="#9b354b" stroke-opacity=".5" stroke-width="16"/><path d="M350 180 C240 105 150 175 150 275 C150 360 545 365 545 265 Q545 210 490 210 Q440 125 385 175" fill="none" stroke="#ffe4d4" stroke-opacity=".7" stroke-width="1"/>${cells('M350 180 C240 105 150 175 150 275 C150 360 545 365 545 265 Q545 210 490 210 Q440 125 385 175 Z',12,12)}<defs><clipPath id="heart-tissue-clip"><ellipse cx="354" cy="234" rx="83" ry="112"/></clipPath></defs><g clip-path="url(#heart-tissue-clip)">${anatomyImage('S5','class="tissue-heart anatomy-motion"')}</g>`;
 if(id==='S6')return `<defs><clipPath id="lung-tissue-clip"><ellipse cx="270" cy="208" rx="70" ry="110"/><ellipse cx="429" cy="208" rx="65" ry="110"/></clipPath></defs><g clip-path="url(#lung-tissue-clip)">${anatomyImage('S6','class="tissue-lungs anatomy-motion"')}</g>${[0,1,2].map(i=>particle('M350 25 L350 137 Q350 155 288 205',i,'#c8f5ff',5,5)).join('')}${[0,1,2].map(i=>particle('M430 220 Q358 175 350 137 L350 25',i,'#e1eee8',4,5)).join('')}`;
 if(id==='S7')return [0,1,2].map(i=>particle('M350 15 L350 94 Q355 148 406 153 Q416 179 363 198 Q324 219 348 238 Q429 259 335 278 Q302 294 410 310',i,'#efd69a',6,16)).join('');
 if(id==='S8')return [-1,1].map(sign=>Array.from({length:3},(_,i)=>particle(sign<0?'M287 145 Q286 222 302 267 Q308 302 333 321':'M424 145 Q408 220 400 270 Q396 303 367 321',i,'#ffe6a4',4,8)).join('')).join('');
 if(id==='S9')return Array.from({length:5},(_,i)=>particle('M240 88 Q269 131 194 179 L184 229 Q190 269 310 302 Q445 342 632 300',i,'#fff5a3',5,5)).join('');
 if(id==='S3')return `<defs><clipPath id="muscle-tissue-clip"><ellipse cx="361" cy="145" rx="29" ry="78"/></clipPath></defs><g clip-path="url(#muscle-tissue-clip)">${anatomyImage('S3','class="tissue-muscle anatomy-motion"')}</g>`;
 if(id==='S1')return Array.from({length:3},(_,i)=>particle('M600 224 Q430 174 180 184 L0 184',i,'#ffeabb',3,7)).join('');
 return `<path class="joint-glow anatomy-motion" d="M475 148 Q491 181 477 223" stroke="#fff1ba" stroke-width="5" fill="none"/>`;
}
export function livingLab(){return `<section class="living-lab" aria-label="Living anatomy close-ups"><div class="section-heading"><div><div class="eyebrow">LIVING ANATOMY / CLOSE-UP LAB</div><h1>See the body at work.</h1><p>Explore all ten systems. Follow flowing cells, air, food, fluid, and nerve signals.</p></div></div><div class="living-tabs" role="group" aria-label="Choose a living system">${Object.entries(anatomyScenes).map(([id,s])=>`<button data-living-system="${id}" aria-pressed="${id==='S4'}">${s.name}</button>`).join('')}</div><div class="living-layout"><div class="living-view"></div><article class="living-notes"><div class="eyebrow">WATCH WHAT HAPPENS</div><h3 data-living-title></h3><p data-living-motion></p><p data-living-detail></p><div class="living-controls"><button data-living-pause>Pause animation</button><button data-living-slow aria-pressed="false">Slow motion</button><button data-living-restart>Restart flow</button></div><p class="living-caption">Detailed illustrative anatomy with animated teaching overlays. Cells are enlarged and timing is slowed to make movement visible.</p></article></div></section>`}
export function mountLivingLab(host){let selected='S4',paused=matchMedia('(prefers-reduced-motion: reduce)').matches,slow=false;
 const view=host.querySelector('.living-view');
 const sync=()=>{for(const animation of view.getAnimations({subtree:true})){animation.playbackRate=slow?.35:1;paused?animation.pause():animation.play()}host.querySelector('[data-living-pause]').textContent=paused?'Play animation':'Pause animation';host.querySelector('[data-living-pause]').setAttribute('aria-pressed',String(paused));host.querySelector('[data-living-slow]').setAttribute('aria-pressed',String(slow));view.dataset.animationState=paused?'paused':'playing';view.dataset.speed=slow?'slow':'normal'};
 const show=()=>{const s=anatomyScenes[selected];view.innerHTML=`<svg viewBox="0 0 700 430" role="img" aria-label="${s.name}: ${s.motion}">${anatomyImage(selected)}<g class="motion-overlay">${anatomyMotion(selected)}</g></svg><span class="living-view-label">${s.name.toUpperCase()} · ANIMATED EXHIBIT</span>`;view.dataset.system=selected;host.querySelector('[data-living-title]').textContent=s.name;host.querySelector('[data-living-motion]').textContent=s.motion;host.querySelector('[data-living-detail]').textContent=s.detail;for(const b of host.querySelectorAll('[data-living-system]'))b.setAttribute('aria-pressed',String(b.dataset.livingSystem===selected));sync()};
 const click=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.livingSystem){selected=b.dataset.livingSystem;show()}else if(b.hasAttribute('data-living-pause')){paused=!paused;sync()}else if(b.hasAttribute('data-living-slow')){slow=!slow;sync()}else if(b.hasAttribute('data-living-restart')){for(const a of view.getAnimations({subtree:true}))a.currentTime=0;sync()}};
 host.addEventListener('click',click);show();return ()=>{host.removeEventListener('click',click);for(const a of view.getAnimations({subtree:true}))a.cancel()};
}
