import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {start,dispatch,observed,journalValid} from '../src/game/learnEngine.js';import {load,DISCLAIMER,record,progress} from '../src/game/state.js';
const send=(s,type,args={})=>dispatch(s,{type,...args});
test('S0 refuses premature needle and wrong prediction; wipes and swabs at exact thresholds',()=>{const s=start('S1');assert.ok(send(s,'dot',{value:1}).tip);send(s,'notice');assert.ok(send(s,'predict',{value:'needle'}).tip);assert.equal(s.step,1);send(s,'predict',{value:'clean'});send(s,'clean',{value:89});assert.equal(s.step,2);send(s,'clean',{value:90});assert.equal(s.step,3);send(s,'swab',{value:84});assert.equal(s.step,3);send(s,'swab',{value:85});assert.equal(s.step,4);assert.ok(send(s,'dot',{value:2}).tip);assert.equal(s.dots,0);assert.ok(send(s,'dot',{value:1,error:25}).tip);for(let i=1;i<=4;i++)send(s,'dot',{value:i,error:20});assert.equal(s.step,5);send(s,'bandage',{distance:49});assert.equal(s.step,5);send(s,'bandage',{distance:48});assert.ok(observed(s));assert.equal(journalValid(s,['shield','','']),false);assert.equal(journalValid(s,['shield','remove dirt','']),true)});
test('S1 casts only after aligned and splinted, snaps within tolerance, wraps to 95%',()=>{const s=start('S2');assert.ok(send(s,'cast',{value:100}).tip);send(s,'xray');assert.ok(s.xray);send(s,'predict',{value:'cast'});assert.equal(s.step,1);send(s,'predict',{value:'align'});send(s,'align',{distance:28});assert.equal(s.step,2);send(s,'align',{distance:27});assert.equal(s.step,3);assert.ok(send(s,'cast',{value:100}).tip);send(s,'splint',{distance:0});send(s,'cast',{value:94});assert.equal(s.step,4);send(s,'cast',{value:95});assert.ok(observed(s));assert.ok(journalValid(s,['holds still','wrong shape']))});
test('S2 requires notice, upright pose, clog clear, nine ordered counts and three respect cards',()=>{const s=start('S6');assert.ok(send(s,'clog').tip);send(s,'notice');send(s,'situp');send(s,'clog');assert.ok(send(s,'breath',{value:3}).tip);for(let i=0;i<9;i++)send(s,'breath',{value:i%3+1});assert.equal(s.step,4);assert.ok(send(s,'respect',{value:2}).tip);for(let i=0;i<3;i++)send(s,'respect',{value:i});assert.ok(observed(s));assert.equal(journalValid(s,['nose tube lungs','wait alone']),false);assert.equal(journalValid(s,['nose trachea bronchi lungs','get a grown-up']),true)});
test('All ten curriculum cards, anatomy, targets, FIX previews and ASCII data exist',()=>{const c=JSON.parse(readFileSync(new URL('../content/CURRICULUM-DATA.json',import.meta.url)));assert.equal(c.systems.length,10);assert.equal(c.systems.filter(s=>s.status==='playable').length,10);for(const s of c.systems){assert.ok(s.targets.length>=3);assert.ok(s.anatomy.length>=3);assert.ok(s.steps.length>=5);assert.ok(s.journal);assert.ok(s.fairTest)}assert.match(readFileSync(new URL('../content/CURRICULUM-DATA.json',import.meta.url),'utf8'),/^[\x00-\x7F]*$/)});
test('Persistence survives reload and storage errors are recoverable',()=>{const data={completed:['S1'],entries:[{id:'S1',answers:['shield','clean first']}],stars:{S1:3},settings:{pip:false}};const stored={getItem:()=>JSON.stringify(data)};assert.equal(load(stored).entries.length,1);assert.deepEqual(load(stored).completed,['S1']);assert.equal(load(stored).settings.pip,false);assert.equal(load({getItem:()=>'{broken'}).entries.length,0);assert.match(DISCLAIMER,/Not real medical care/)});

test("Failed journal storage rolls back entries and unlocks",()=>{const before=progress;const previous=globalThis.localStorage;globalThis.localStorage={setItem(){throw new Error("Storage unavailable")}};assert.equal(record("S1",["shield","clean first"],"Learn"),false);assert.equal(progress,before);assert.deepEqual(progress.completed,[]);assert.deepEqual(progress.entries,[]);globalThis.localStorage=previous});
