import {chapters,emergencyLessons} from './game/chapters.js';
import {currentChapterStep,chapterControls,emergencyHub} from './game/chapterView.js';
import './styles.css';
import curriculum from '../content/CURRICULUM-DATA.json';
import {DISCLAIMER,progress,persist,record,escape} from './game/state.js';
import {slices,start,dispatch,observed,journalValid} from './game/learnEngine.js';
import {vitals} from './game/vitals.js';import {tray} from './game/tray.js';import {checklist} from './game/checklist.js';import {tips} from './game/pip.js';import {journal,archive} from './game/journal.js';import {stub} from './game/stubs.js';import {board,gels,swabs,dots} from './game/boards.js';import {layers,mountLab} from './game/freeLab.js';
const app=document.querySelector('#app'),systems=curriculum.systems;
let screen='boot',mode=progress.lastMode||'Learn',system=systems[0],session=null,layer='Skin',dispose=()=>{},tip='',painted=new Set(),wiped=new Set(),wrapped=new Set();
const badges={S1:'◈',S2:'⌁',S3:'≋',S4:'◌',S5:'♡',S6:'♧',S7:'↝',S8:'◇',S9:'✧',S10:'⬡',E1:'+',E2:'+',E3:'+'};
function chirp(){if(!progress.settings.sound)return;try{const ctx=new AudioContext();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(520,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(740,ctx.currentTime+.15);gain.gain.setValueAtTime(.035,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.22);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.22);osc.onended=()=>ctx.close()}catch{}}
const header=()=>`<header><button class="brand" data-nav="home" aria-label="Med Quest home"><span class="brand-mark">+</span><span>MED QUEST<small>BODY OPS ACADEMY</small></span></button><nav><button class="${screen==='map'?'active':''}" data-nav="map">Missions</button><button class="${screen==='lab'?'active':''}" data-nav="lab">Free Lab</button><button class="${screen==='archive'?'active':''}" data-nav="archive">Journal <span class="count">${progress.entries.length}</span></button><button data-nav="settings" aria-label="Settings">⚙</button></nav><div class="rank"><span class="rank-dot"></span> ${progress.completed.filter(id=>id.startsWith('S')).length}/10 discoveries</div></header>`;
const foot=()=>`<footer><span>Body Ops Academy / Class of curious minds</span><span>LEARN · EXPLORE · DISCOVER</span><p>${DISCLAIMER}</p></footer>`;
function boot(){return `<div class="boot"><div class="seal">+<span>BODY OPS<br>ACADEMY</span></div><div class="eyebrow">WELCOME, JUNIOR EXPLORER</div><h1>A little curiosity.<br>A whole world inside.</h1><p class="intro">Discover how your body works. Practice gentle missions, explore anatomy, and keep a journal of what you learn.</p><div class="boot-disclaimer"><b>Before we enter the academy</b><p>${DISCLAIMER}</p></div><button class="primary big" data-action="enter">Enter Academy <span>→</span></button><small>Original learning game · No accounts · Progress saved on this device</small></div>`}
function home(){return `<section class="hero"><div><div class="eyebrow"><span class="dot"></span> THE ACADEMY IS OPEN</div><h1>Your next adventure<br>is on the inside.</h1><p>Meet the systems that make you, you.<br>Learn the science. Try a mission. Make a discovery.</p><div class="actions"><button class="primary" data-mode="Learn">Start learning <span>→</span></button><button class="quiet" data-nav="lab">Explore the body</button></div><div class="hero-stats"><span><b>10</b> body systems</span><span><b>10</b> playable missions</span><span><b>∞</b> curiosity</span></div></div><div class="hero-art museum-hero"><img src="${import.meta.env.BASE_URL}assets/anatomy/MQ_R6_museum_hero.webp" alt="A volunteer beside a clean acrylic anatomy exhibit" fetchpriority="high" /></div></section><section><div class="section-heading"><div><div class="eyebrow">CHOOSE YOUR PATH</div><h2>How will you discover today?</h2></div><span>Four ways to explore.</span></div><div class="modes">${[['Learn','01','One step at a time','Guided missions, helpful tips, and no time pressure.'],['Arcade','02','Practice & collect stars','Replay a completed Learn mission for practice stars.'],['Free Lab','03','Follow your curiosity','Turn the anatomy layers on and tap a part.'],['Emergency','04','Stay calm, think clearly','Practice safe help decisions in three calm stories.']].map(([n,i,t,d])=>`<button class="mode-card" data-mode="${n}"><span class="eyebrow">${i} / ${n.toUpperCase()}</span><h3>${t}</h3><p>${d}</p><span class="card-arrow">↗</span></button>`).join('')}</div></section><section class="fix-banner"><div class="eyebrow">THE ACADEMY WAY</div><h2>Notice. Predict. Act. Observe. Journal.</h2><p>Find the problem → Identify a tool → eXecute in order → Check the outcome → Write your discovery.</p></section>`}
function map(){return `<div class="section-heading"><div><div class="eyebrow">${mode.toUpperCase()} / SYSTEMS LADDER</div><h1>Ten systems. One amazing you.</h1><p>Start with skin, bones, or breathing. Explore every curriculum card.</p></div><button class="quiet" data-nav="home">Change mode</button></div><div class="systems">${systems.map(s=>{const done=progress.completed.includes(s.id),lock=mode==='Arcade'&&s.status==='playable'&&!done;return `<button class="system-card ${done?'completed':''}" data-system="${s.id}"><span class="system-icon">${badges[s.id]}</span><div class="eyebrow">SYSTEM ${String(s.order).padStart(2,'0')}</div><h3>${escape(s.name)}</h3><p>${escape(s.operation)}</p><span class="status">${s.status==='stub'?'Teach card / future operation':lock?'Finish Learn to unlock Arcade':done?mode==='Arcade'?`${progress.stars[s.id]||0}/3 practice stars`:'✓ Discovery saved':'Playable mission'} <span>→</span></span></button>`}).join('')}</div>`}
const museumArtwork={"S1":"R1","S2":"R4","S3":"R13","S4":"R10","S5":"R2","S6":"R3","S7":"R14","S8":"R15","S9":"R16","S10":"R17"};
function teach(){return `<button class="back quiet" data-nav="${mode==='Emergency'?'emergency':'map'}">← ${mode==='Emergency'?'Help stories':'Systems ladder'}</button><div class="teach-layout"><div><div class="eyebrow">${mode==='Emergency'?'STORY':'SYSTEM'} ${system.order} / ${mode.toUpperCase()}</div><h1>${escape(system.name)}</h1><p class="lead">${escape(system.theme)}</p><figure class="teach-illustration"><img src="${import.meta.env.BASE_URL}assets/anatomy/${museumArtwork[system.id]?`MQ_${museumArtwork[system.id]}_museum.webp`:'MQ_R6_museum_hero.webp'}" alt="${escape(system.name)} museum illustration" /><figcaption>Illustrative museum model · Simplified for learning</figcaption></figure></div><article class="teach-card"><div class="eyebrow">MEET YOUR SYSTEM</div><h2>What will you learn?</h2><ul class="targets">${system.targets.map(x=>`<li>${escape(x)}</li>`).join('')}</ul><h3>Parts to notice</h3><div class="chips">${system.anatomy.map(x=>`<span>${escape(x)}</span>`).join('')}</div><h3>Your mission</h3><p>${escape(system.scenarios[0])}</p><div class="fair-test"><b>A scientist's question</b><p>${escape(system.fairTest)}</p></div>${mode==='Arcade'&&system.status==='playable'&&!progress.completed.includes(system.id)?'<p>Complete this mission in Learn and save its journal to unlock Arcade practice.</p><button class="primary" data-action="learn-instead">Open in Learn</button>':`<button class="primary" data-action="start">${system.status==='playable'?'Begin '+escape(system.operation):'Open the planned FIX board'} →</button>`}</article></div>`}
function controls(){const s=session;if(observed(s))return `<div class="success"><span>✓</span><h3>${s.id==='S1'?'Shield protected!':s.id==='S2'?'Straight and steady!':chapters[s.id]?.success||'A clear path, calm breaths!'}</h3><p>Observe the green vitals. What changed?</p><button class="primary" data-action="journal">Write my journal →</button></div>`;
 if(chapters[s.id])return chapterControls(s);
 if(s.id==='S1'){if(s.step===0)return '<button class="primary" data-game="notice">I see the cut</button>';if(s.step===1)return '<p>What should we do first?</p><button class="primary" data-game="predict" data-value="clean">Clean first</button><button class="quiet" data-game="predict" data-value="needle">Stitch first</button>';if(s.step===2)return `<p>Wipe or tap each blue gel blob. Select Sponge first.</p><div class="meter"><span style="width:${s.clean}%"></span></div><b>Clean ${s.clean}% / goal 90%</b><div class="assist"><button data-assist="clean">Clean next blue blob (keyboard)</button></div>`;if(s.step===3)return `<p>Drag the swab across the gold guide or tap each guide spot.</p><div class="meter"><span style="width:${s.swab}%"></span></div><b>Guide coverage ${s.swab}% / goal 85%</b><div class="assist"><button data-assist="swab">Swab next guide spot (keyboard)</button></div>`;if(s.step===4)return `<p>Follow the dashed guide. Tap the dots in order or drag from dot to dot.</p><div class="dot-buttons">${dots.map((_,i)=>`<button data-game="dot" data-value="${i+1}" ${i<s.dots?'disabled':''}>Dot ${i+1}</button>`).join('')}</div>`;if(s.step===5)return '<p>Drag the bandage into the glowing outline.</p><button data-assist="bandage">Place bandage in outline (keyboard)</button>'}
 if(s.id==='S2'){if(s.step===0)return '<button class="primary" data-game="xray">Turn X-ray on</button>';if(s.step===1)return '<p>Which order helps the bone line up?</p><button class="primary" data-game="predict" data-value="align">Align before cast</button><button class="quiet" data-game="predict" data-value="cast">Cast first</button>';if(s.step===2)return '<p>Drag the loose bone fragment up and left to its ghost.</p><button data-assist="align">Align fragment to ghost (keyboard)</button>';if(s.step===3)return '<p>Slide the splint under the aligned bone.</p><button data-assist="splint">Place splint in outline (keyboard)</button>';if(s.step===4)return `<p>Swipe or tap the cast strips to wrap the shell.</p><div class="meter"><span style="width:${s.wrap}%"></span></div><b>Wrap ${s.wrap}% / goal 95%</b><div class="assist"><button data-assist="cast">Wrap next strip (keyboard)</button></div>`}
 if(s.id==='S6'){if(s.step===0)return '<button class="primary" data-game="notice">I notice the low O2 band</button>';if(s.step===1)return '<p>Match the upright pose on the diagram.</p><button class="primary" data-game="situp">Sit the pretend patient up</button>';if(s.step===2)return '<p>Tap the soft blue clog in the diagram.</p><button data-game="clog">Lift the pretend soft clog (keyboard)</button>';if(s.step===3)return `<div class="breath-cue"><div class="breath-orb">${s.count%3+1}</div><h3>${['Belly expands','Breathe gently','Belly relaxes'][s.count%3]}</h3><p>Cycle ${Math.min(3,Math.floor(s.count/3)+1)} of 3 · ${s.count}/9 calm counts</p><button class="primary" data-game="breath" data-value="${s.count%3+1}">Count ${s.count%3+1}</button></div>`;if(s.step===4)return `<p>Some kids use a helper puff with a grown-up. Practice the respect sequence.</p><div class="respect">${['Call adult','Shake the prop','Adult helps'].map((v,i)=>`<button data-game="respect" data-value="${i}" ${i<s.cards?'disabled':''}>${i<s.cards?'✓ ':''}${v}</button>`).join('')}</div><p class="adult">Ask a grown-up. Not a game dose.</p>`}return ''}
function operation(){return `<button class="back quiet" data-nav="${mode==='Emergency'?'emergency':'map'}">← ${mode==='Emergency'?'Help stories':'Academy map'}</button><div class="op-heading"><div><div class="eyebrow">${mode.toUpperCase()} / ${system.name.toUpperCase()}</div><h1>${escape(system.operation)}</h1></div><button class="quiet" data-action="restart">Restart mission</button></div><div class="mission-spine"><span class="${session.step===0?'on':''}">Notice</span><span class="${session.step===1&&session.id!=='S6'?'on':''}">Predict</span><span class="${session.step>=2&&!observed(session)?'on':''}">Act</span><span class="${observed(session)?'on':''}">Observe</span><span>Journal</span></div><div class="op-layout"><aside><div class="eyebrow">YOUR FIX CHECKLIST</div><ol class="checklist">${checklist(session)}</ol><div class="pip" ${progress.settings.pip?'':'hidden'}><div class="pip-face">•‿•</div><b>Pip, your lab coach</b><p id="pip-text" role="status" aria-live="polite">${escape(tip||tips[session.id]?.[session.step]||'Keep exploring!')}</p></div><button class="quiet small" data-action="toggle-pip">${progress.settings.pip?'Hide':'Show'} Pip</button></aside><div class="workbench"><div class="vitals">${vitals(session)}</div>${session.id==='S6'?'<div class="adult">Real cannot-breathe = get an adult / call for help. This is a pretend diagram.</div>':''}<div class="stage">${board(session)}</div><div class="tool-tray">${tray(session)}</div><div class="board-controls" aria-live="polite">${controls()}</div><p id="gentle-tip" class="gentle-tip" role="status">${escape(tip)}</p></div></div>${journal(session)}`}
function lab(){return `<div class="section-heading"><div><div class="eyebrow">FREE LAB / ANATOMY EXHIBIT</div><h1>Peel back a layer of wonder.</h1><p>Tap a body part or use the labels. Every part has a job.</p></div></div><div class="layer-tabs" role="group" aria-label="Anatomy layers">${Object.keys(layers).map(l=>`<button data-layer="${l}" aria-pressed="${layer===l}" class="${layer===l?'active':''}">${l}</button>`).join('')}</div><div class="lab-layout"><div id="anatomy-3d"><span class="exhibit-label">${layer.toUpperCase()} / INTERACTIVE 3D EXHIBIT</span></div><article class="lab-notes"><div class="eyebrow">FOLLOW YOUR CURIOSITY</div><h2>${layer} layer</h2><div class="part-buttons">${layers[layer].map(([name],i)=>`<button data-part="${i}">${name} <span>→</span></button>`).join('')}</div><div id="part-fact" class="fact-card"></div><div class="fair-test"><b>Try a fair test</b><p id="experiment-copy">Use the ${layer} labels to discover what each part does.</p><button data-action="experiment">Compare two pretend trials</button><p id="experiment-result"></p></div><p>Base anatomy is open for exploration. Saved Learn discoveries unlock Arcade practice and your discovery badges.</p></article></div>`}
function settings(){return `<div class="settings"><div class="eyebrow">MAKE YOURSELF AT HOME</div><h1>Your academy settings.</h1><label><input type="checkbox" data-setting="sound" ${progress.settings.sound?'checked':''}> Soft success sounds</label><label><input type="checkbox" data-setting="pip" ${progress.settings.pip?'checked':''}> Show Pip's coaching tips</label><p>Reduced motion follows your device's accessibility setting.</p><p>Journal and stars save locally on this browser. No personal information or account required.</p></div>`}
function navigate(s){screen=s;tip='';render();window.scrollTo({top:0,behavior:'instant'})}
function render(){dispose();dispose=()=>{};app.innerHTML=screen==='boot'?boot():header()+`<main>${screen==='home'?home():screen==='map'?map():screen==='teach'?teach():screen==='op'?operation():screen==='stub'?stub(system):screen==='lab'?lab():screen==='archive'?archive():screen==='settings'?settings():screen==='complete'?`<section class="completion"><div class="eyebrow">DISCOVERY SAVED</div><div class="completion-seal">✓</div><h1>You made a discovery.</h1><p>${escape(system.operation)} complete. Your journal is safe on this device.</p>${mode==='Arcade'?`<div class="stars">${'★'.repeat(Math.max(1,3-Math.floor(session.mistakes/3)))}</div><p>Practice stars celebrate curiosity, not medical skill.</p>`:mode==='Emergency'?'<p>You practiced getting help safely.</p>':'<p>Arcade practice is now unlocked for this system.</p>'}<div class="actions"><button class="primary" data-nav="${mode==='Emergency'?'emergency':'map'}">${mode==='Emergency'?'Choose another story':'Choose another mission'} →</button><button class="quiet" data-nav="archive">Read my journal</button></div></section>`:emergencyHub(progress)}</main>`+foot();if(screen==='op'){restorePaint();bindStage();document.querySelector('#journal-form').addEventListener('submit',saveJournal)}if(screen==='lab'){dispose=mountLab(document.querySelector('#anatomy-3d'),layer,showPart);showPart(0)}}
function restorePaint(){for(const i of wiped)document.querySelector(`[data-gel="${i}"]`)?.remove();for(const i of painted)document.querySelector(`[data-swab="${i}"]`)?.setAttribute('fill','#55b895');for(const i of wrapped)document.querySelector(`[data-wrap="${i}"]`)?.setAttribute('fill','#f7f6ed')}
function tell(message){tip=message;const p=document.querySelector('#pip-text'),g=document.querySelector('#gentle-tip');if(p)p.textContent=message;if(g)g.textContent=message}
function perform(a){const r=dispatch(session,a);if(r.tip){tell(r.tip);return false}tip='';if(r.changed){chirp();if(!a.deferRender)render()}else if(a.type==='chapter'&&!a.deferRender){render()}else if(['dot','breath','respect','xray'].includes(a.type)&&!a.deferRender){render()}return true}
function selectTool(id){if(chapters[session.id]){const step=currentChapterStep(session);if(step?.tool!==id){tell('Follow the current checklist step before choosing this tool.');session.mistakes++;return}session.tool=id;render();return}if(session.id==='S2'&&id==='xray'){perform({type:'xray'});return}const expected=session.id==='S1'?{2:'sponge',3:'swab',4:'needle',5:'bandage'}:session.id==='S2'?{2:'align',3:'splint',4:'cast'}:{1:'situp',2:'forceps',3:'breaths',4:'inhaler'};if(expected[session.step]!==id){tell(id==='needle'?'Clean at least 90% and swab at least 85% before the needle.':id==='cast'?'Align the bone, then splint, then cast.':`Follow the checklist first. ${tips[session.id]?.[session.step]||'Observe the outcome.'}`);session.mistakes++;return}session.tool=id;render()}
function requireTool(id){if(session.tool===id)return true;tell(`Select ${slices[session.id].spec.tools.find(t=>t[0]===id)?.[1]||id} in the tray first.`);return false}
function paint(type,index){const data=type==='clean'?wiped:type==='swab'?painted:wrapped,tool=type==='clean'?'sponge':type==='swab'?'swab':'cast';if(!requireTool(tool))return;if(data.has(index))return;const copy=new Set(data);copy.add(index);const value=copy.size*5;if(perform({type,value})){data.add(index);if(screen==='op'){restorePaint();const meter=document.querySelector('.meter span');if(meter)meter.style.width=value+'%';const b=document.querySelector('.board-controls > b');if(b)b.textContent=`${type==='clean'?'Clean':type==='swab'?'Guide coverage':'Wrap'} ${value}% / goal ${type==='clean'?90:type==='swab'?85:95}%`}}}
function assist(type){const tool={clean:'sponge',swab:'swab',cast:'cast',align:'align',splint:'splint',bandage:'bandage'}[type];if(!requireTool(tool))return;if(['clean','swab','cast'].includes(type)){const data=type==='clean'?wiped:type==='swab'?painted:wrapped;const next=Array.from({length:20},(_,i)=>i).find(i=>!data.has(i));if(next!==undefined)paint(type,next)}else perform({type,distance:0})}
function point(e,svg){const p=new DOMPoint(e.clientX,e.clientY);return p.matrixTransform(svg.getScreenCTM().inverse())}
function bindStage(){const svg=document.querySelector('#stage-svg');if(chapters[session.id]){bindChapterStage(svg);return}let drag=null,stitch=null,pointerDown=false;svg.addEventListener('pointerdown',e=>{pointerDown=true;const p=point(e,svg);const g=e.target.closest('[data-drag]');if(g){const type=g.dataset.drag;if(!requireTool(type))return;const origin=type==='align'?[390,262]:type==='splint'?[130,362]:[105,340];drag={g,type,start:p,origin,x:origin[0],y:origin[1]};svg.setPointerCapture(e.pointerId)}else if(session.id==='S1'&&session.step===4&&session.tool==='needle'){const i=dots.findIndex(d=>Math.hypot(p.x-d.x,p.y-d.y)<26);if(i>=0){if(i===session.dots-1){stitch={last:i,error:0}}else if(perform({type:'dot',value:i+1,error:0,deferRender:true})&&session.step===4){stitch={last:i,error:0}}svg.setPointerCapture(e.pointerId)}}else handlePoint(p)});svg.addEventListener('pointermove',e=>{if(!pointerDown)return;const p=point(e,svg);if(drag){drag.x=drag.origin[0]+p.x-drag.start.x;drag.y=drag.origin[1]+p.y-drag.start.y;drag.g.setAttribute('transform',`translate(${drag.x} ${drag.y})`)}else if(stitch){const from=dots[stitch.last],to=dots[stitch.last+1];if(!to)return;const vx=to.x-from.x,vy=to.y-from.y,t=Math.max(0,Math.min(1,((p.x-from.x)*vx+(p.y-from.y)*vy)/(vx*vx+vy*vy)));stitch.error=Math.max(stitch.error,Math.hypot(p.x-from.x-t*vx,p.y-from.y-t*vy));if(Math.hypot(p.x-to.x,p.y-to.y)<22){perform({type:'dot',value:stitch.last+2,error:stitch.error,deferRender:true});stitch={...stitch,last:stitch.last+1,error:0,finished:true}}}else handlePoint(p)});svg.addEventListener('pointerup',()=>{pointerDown=false;if(drag){const target=drag.type==='align'?[323,156]:drag.type==='splint'?[342,237]:[338,217];const distance=Math.hypot(drag.x-target[0],drag.y-target[1]);const d=drag;drag=null;perform({type:d.type,distance});if(!observed(session))render()}if(stitch)render();stitch=null});svg.addEventListener('pointercancel',()=>{pointerDown=false;drag=null;stitch=null;render()});
 function handlePoint(p){if(session.id==='S1'&&session.step===2){gels.forEach((d,i)=>{if(Math.hypot(p.x-d.x,p.y-d.y)<24)paint('clean',i)})}else if(session.id==='S1'&&session.step===3){swabs.forEach((d,i)=>{if(Math.hypot(p.x-d.x,p.y-d.y)<18)paint('swab',i)})}else if(session.id==='S1'&&session.step===4){const i=dots.findIndex(d=>Math.hypot(p.x-d.x,p.y-d.y)<26);if(i>=0&&requireTool('needle'))perform({type:'dot',value:i+1,error:0})}else if(session.id==='S2'&&session.step===4&&p.y>=120&&p.y<=260){const i=Math.floor((p.x-200)/14);if(i>=0&&i<20)paint('cast',i)}else if(session.id==='S6'&&session.step===2&&Math.hypot(p.x-350,p.y-154)<35&&requireTool('forceps'))perform({type:'clog'})}
}
function bindChapterStage(svg){
 const current=currentChapterStep(session);let drag=null,holding=false;
 const invoke=extras=>perform({type:'chapter',step:session.step,...extras});
 svg.addEventListener('click',e=>{const value=e.target.closest('[data-chapter-value]'),item=e.target.closest('[data-chapter-item]');if(value)invoke({value:value.dataset.chapterValue});if(item)invoke({item:Number(item.dataset.chapterItem)})});
 svg.addEventListener('pointerdown',e=>{const g=e.target.closest('[data-chapter-drag]');if(g&&current){if(!requireTool(current.tool))return;const p=point(e,svg);drag={g,start:p,origin:current.origin,x:current.origin[0],y:current.origin[1]};svg.setPointerCapture(e.pointerId)}else if(e.target.closest('[data-chapter-hold]')&&current){if(current.tool&&!requireTool(current.tool))return;holding=true;invoke({value:'start',deferRender:true});svg.setPointerCapture(e.pointerId)}});
 svg.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e,svg);drag.x=drag.origin[0]+p.x-drag.start.x;drag.y=drag.origin[1]+p.y-drag.start.y;drag.g.setAttribute('transform',`translate(${drag.x} ${drag.y})`)});
 svg.addEventListener('pointerup',()=>{if(drag){const distance=Math.hypot(drag.x-current.target[0],drag.y-current.target[1]);drag=null;invoke({value:'snap',distance})}if(holding){holding=false;invoke({value:'finish'})}});
 svg.addEventListener('pointercancel',()=>{drag=null;holding=false;render()});
 if(current?.kind==='wait'){const timer=setInterval(()=>{if(session.waitStarted===undefined)return;const elapsed=Date.now()-session.waitStarted,percent=Math.min(100,elapsed/current.duration*100);const meter=document.querySelector('#chapter-wait-meter'),status=document.querySelector('#chapter-wait-status');if(meter)meter.style.width=percent+'%';if(status)status.textContent=percent>=100?'Demonstration ready. Check the outcome.':'Watching the short demonstration…';},100);dispose=()=>clearInterval(timer)}
}
function saveJournal(e){e.preventDefault();const answers=slices[session.id].spec.prompts.map((_,i)=>e.target.elements['answer'+i].value.trim());if(!journalValid(session,answers)){document.querySelector('#journal-error').textContent=(session.id==='S6'||chapters[session.id]?.safetyAnswer!==undefined)?'Write both answers and include getting a grown-up / calling for help in your real emergency answer.':'Write at least two answers before saving.';return}const saved=record(session.id,answers,mode,Math.max(1,3-Math.floor(session.mistakes/3)));if(!saved){document.querySelector('#journal-error').textContent='This browser could not save your journal. Enable local storage and try again.';return}chirp();navigate('complete')}
function showPart(i){const [name,fact,id]=layers[layer][i];document.querySelector('#part-fact').innerHTML=`<div class="eyebrow">PART ${i+1} / ${layer.toUpperCase()}</div><h3>${name}</h3><p>${fact}</p><button class="quiet" data-system="${id}">Explore this system →</button>`}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.nav){if(b.dataset.nav==='map'&&mode==='Emergency'){mode='Learn';progress.lastMode=mode;persist()}navigate(b.dataset.nav);return}if(b.dataset.mode){mode=b.dataset.mode;progress.lastMode=mode;persist();navigate(mode==='Free Lab'?'lab':mode==='Emergency'?'emergency':'map');return}if(b.dataset.system){system=[...systems,...emergencyLessons].find(s=>s.id===b.dataset.system);navigate('teach');return}if(b.dataset.layer){layer=b.dataset.layer;navigate('lab');return}if(b.dataset.part!==undefined){showPart(Number(b.dataset.part));return}if(b.dataset.tool){selectTool(b.dataset.tool);return}if(b.dataset.assist){assist(b.dataset.assist);return}if(b.hasAttribute('data-chapter-action')){const step=Number(b.dataset.step);let action={type:'chapter',step,value:b.dataset.value};if(b.dataset.item!==undefined)action.item=Number(b.dataset.item);if(b.dataset.distance!==undefined)action.distance=Number(b.dataset.distance);if(b.hasAttribute('data-range-check'))action.value=Number(document.querySelector('#chapter-range').value);perform(action);return}if(b.dataset.game){const type=b.dataset.game;const tool={dot:'needle',situp:'situp',clog:'forceps',breath:'breaths',respect:'inhaler'}[type];if(tool&&!requireTool(tool))return;perform({type,value:['dot','breath','respect'].includes(type)?Number(b.dataset.value):b.dataset.value,error:0});return}switch(b.dataset.action){case 'enter':navigate('home');break;case 'start':case 'restart':if(system.status==='stub')navigate('stub');else{session=start(system.id);wiped=new Set();painted=new Set();wrapped=new Set();navigate('op')}break;case 'learn-instead':mode='Learn';progress.lastMode=mode;persist();navigate('teach');break;case 'journal':document.querySelector('#journal-dialog').showModal();break;case 'close-journal':document.querySelector('#journal-dialog').close();break;case 'toggle-pip':progress.settings.pip=!progress.settings.pip;persist();render();break;case 'experiment':document.querySelector('#experiment-result').textContent=layer==='Skin'?'Pretend trial A: clean sponge leaves 0 gel markers. Trial B: dirty sponge leaves 6. Keep the same board and wipe count. Which sponge left less mess?':layer==='Bone'?'Pretend trial A: snug cast keeps 0 gaps. Trial B: loose cast leaves 2 gaps after the same gentle jiggle. Which stayed aligned?':layer==='Organs'?'Pretend trial A: belly breath adds 3 calm chips. Trial B: shoulder shrug adds 1. Use the same number of cycles. Which helps this pretend calm meter more?':'Choose one thing to change and keep the rest the same. Compare what you observe in two pretend trials.';break;}});
app.addEventListener('change',e=>{if(e.target.dataset.setting){progress.settings[e.target.dataset.setting]=e.target.checked;persist()}});
render();
